[phases.setup]
nixPkgs = ["...", "nodejs-22_x"]
aptPkgs = [
  "libglib2",
  "nss",
  "nspr",
  "atk",
  "at-spirit-bridge",
  "cups",
  "libdrm",
  "libxkbcommon",
  "libXcomposite",
  "libXdamage",
  "libXext",
  "libXfixes",
  "libXrandr",
  "mesa",
  "pango",
  "cairo",
  "alsa-lib"
]